#!/usr/bin/env python3
"""Generate ACME include files into build/gen/: fade tables, SID note table,
shuffled dissolve order, and the unrolled 200-line FLI displayer body.
"""

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import c64color

PAL_CLOCK = 985248.0


def bytes_block(label, data, per_line=16):
    out = [f"{label}"]
    data = list(data)
    for i in range(0, len(data), per_line):
        out.append("        !byte " + ",".join(f"${b:02x}" for b in data[i:i + per_line]))
    return "\n".join(out) + "\n"


def fade256():
    ft = c64color.fade_table()
    return [(ft[v >> 4] << 4) | ft[v & 15] for v in range(256)]


def note_tables():
    lo, hi = [], []
    for n in range(96):
        f = 440.0 * 2 ** ((n - 57) / 12)
        reg = min(65535, round(f * 16777216 / PAL_CLOCK))
        lo.append(reg & 0xFF)
        hi.append(reg >> 8)
    return lo, hi


def fli_lines():
    """Unrolled FLI display body: exactly 23 CPU cycles per line.

    Image line n displays at raster 51+n. Line 0's badline is a normal one
    (yscroll 3 set ahead by the entry code, initializing RC=0); iterations
    n=1..199 create LATE badlines: the $D011 write (yscroll = raster&7)
    lands at cycle ~15-16, after the VIC's cycle-14 check, so the row
    counter RC is never reset and free-runs 0-7 -- that's what advances
    VCBASE every 8th line (and what causes the FLI bug in columns 0-2,
    which our images keep black). Filler comes first so the writes land at
    the end of each 23-cycle block.
    """
    lines = []
    for n in range(1, 200):
        d018 = 0x08 | ((n & 7) << 4)
        d011 = 0x38 | ((3 + n) & 7)
        lines.append("        nop\n        nop\n        nop\n        nop\n"
                     "        bit $ea\n"
                     f"        lda #${d018:02x}\n"
                     f"        sta $d018\n"
                     f"        lda #${d011:02x}\n"
                     f"        sta $d011")
    return "; generated by gen_tables.py -- do not edit\n" + "\n".join(lines) + "\n"


def write_all(dest):
    dest = pathlib.Path(dest)
    dest.mkdir(parents=True, exist_ok=True)
    ft = c64color.fade_table()
    (dest / "fade_tables.asm").write_text(
        bytes_block("fade16", ft) + bytes_block("fade256", fade256()))
    lo, hi = note_tables()
    (dest / "note_table.asm").write_text(
        bytes_block("note_lo", lo) + bytes_block("note_hi", hi))
    (dest / "fli_lines.asm").write_text(fli_lines())


if __name__ == "__main__":
    write_all(pathlib.Path(__file__).resolve().parent / "build" / "gen")
    print("wrote build/gen/{fade_tables,note_table,fli_lines}.asm")
